import React from 'react'

const EcommerceContext = React.createContext({
  cartList: [],
  removeAllCartItems: () => {},
  addCartItem: () => {},
  removeCartItem: () => {},
  incrementCartItemQuantity: () => {},
  decrementCartItemQuantity: () => {},
  productItemDetailsData: {},
  quantityIncrement: () => {},
  quantityDecrement: () => {},
  searchInput: '',
  clickingSearchButton: () => {},
  changingSearchInput: () => {},
  allProductsList: [],
  addProduct: [],
  buynowClickingBtn: () => {},
  buyNowItem: {},
  titleInput: '',
  thumbnailInput: '',
  descriptionInput: '',
  priceInput: '',
  brandInput: '',
  stockInput: '',
  categoryInput: '',
  ratingInput: '',
  discountInput: '',
  image1Input: '',
  image2Input: '',
  image3Input: '',
  image4Input: '',
  newList: [],
  isShowAllProducts: false,
  ClickHighlting: () => {},
  onChangeTitle: () => {},
  onChangeDesacription: () => {},
  onChangePrice: () => {},
  onChangeBrand: () => {},
  onChangeCategory: () => {},
  onChangeDiscountPercentage: () => {},
  onChangeStock: () => {},
  onChangeThumbnail: () => {},
  submittingForm: () => {},
  onChangeImage1: () => {},
  onChangeImage2: () => {},
  onChangeImage3: () => {},
  onChangeImage4: () =>{},
  onChangeRating: () => {},
  activeCategoryId: '',
  changingCategory: () => {},
  clickingCategory: () => {},
  categoriesProducts: [],
  categoriesList: [],
  searchProductsList: [],
  showAddingProduct: false,
  clickingPostButton: () => {},
})

export default EcommerceContext